# DeepFake Shield — Complete Colab Notebook

## CELL 1 — Mount Google Drive

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

---

# CELL 2 — Check GPU

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "GPU memory:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2
        ),
        "GB"
    )
else:
    print("❌ GPU NOT AVAILABLE")
    print("Go to Runtime → Change runtime type → T4 GPU")

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
GPU memory: 14.56 GB

### You want to see something like:

```text
CUDA available: True
GPU: Tesla T4
GPU memory: 15.0 GB
```

**If CUDA is `False`, stop here and enable GPU.**

---

In [ ]:
%cd /content

!git clone https://github.com/GokulM8/deep-fake-shield.git

%cd /content/deep-fake-shield

!git status
!ls

/content
Cloning into 'deep-fake-shield'...
remote: Enumerating objects: 216, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 216 (delta 38), reused 211 (delta 33), pack-reused 0 (from 0)
Receiving objects: 100% (216/216), 1.23 MiB | 16.86 MiB/s, done.
Resolving deltas: 100% (38/38), done.
/content/deep-fake-shield
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
 artifacts   datasets		    docs       ml	   reports
 backend    'DeepFake Shield.pdf'   frontend   README.md   scripts

# CELL 3 — Define all paths

In [ ]:
from pathlib import Path

# Repository cloned in Colab
REPO_ROOT = Path("/content/deep-fake-shield")

# Dataset permanently stored in Google Drive
DATA_ROOT = Path(
    "/content/drive/MyDrive/DeepFake-Shield (1)/datasets/raw"
)

# Existing split files
SPLITS_ROOT = REPO_ROOT / "artifacts" / "splits"

TRAIN_CSV = SPLITS_ROOT / "train.csv"
VAL_CSV = SPLITS_ROOT / "val.csv"
TEST_CSV = SPLITS_ROOT / "test.csv"

# Output directories
EXPERIMENTS_ROOT = REPO_ROOT / "artifacts" / "experiments"
EVALUATION_ROOT = REPO_ROOT / "artifacts" / "evaluation"

# Permanent model location in Drive
DRIVE_MODEL_ROOT = Path(
    "/content/drive/MyDrive/DeepFake-Shield/models"
)

DRIVE_MODEL_ROOT.mkdir(parents=True, exist_ok=True)

print("Repository:", REPO_ROOT)
print("Dataset:", DATA_ROOT)
print("Splits:", SPLITS_ROOT)

Repository: /content/deep-fake-shield
Dataset: /content/drive/MyDrive/DeepFake-Shield (1)/datasets/raw
Splits: /content/deep-fake-shield/artifacts/splits

---

# CELL 4 — Verify repository

In [ ]:
print("Repository exists:", REPO_ROOT.exists())

if REPO_ROOT.exists():
    print("\nRepository contents:\n")

    for item in sorted(REPO_ROOT.iterdir()):
        print(
            "📁" if item.is_dir() else "📄",
            item.name
        )

Repository exists: True

Repository contents:

📄 .env.example
📁 .git
📄 .gitignore
📄 DeepFake Shield.pdf
📄 README.md
📁 artifacts
📁 backend
📁 datasets
📁 docs
📁 frontend
📁 ml
📁 reports
📁 scripts

You should see your project files.

---

# CELL 5 — Verify training scripts

In [ ]:
SCRIPTS_ROOT = REPO_ROOT / "scripts"

required_scripts = [
    "inspect_dataset.py",
    "split_dataset.py",
    "train_baseline.py",
    "evaluate_baseline.py",
    "infer_video.py"
]

print("Checking scripts...\n")

for script in required_scripts:

    path = SCRIPTS_ROOT / script

    if path.exists():
        print("✅", script)
    else:
        print("❌", script)

Checking scripts...

✅ inspect_dataset.py
✅ split_dataset.py
✅ train_baseline.py
✅ evaluate_baseline.py
✅ infer_video.py

You already confirmed these exist, so this should be all green.

---

# CELL 6 — Verify dataset

In [ ]:
!ls -lah /content/drive/MyDrive

total 372M
drwx------ 8 root root 4.0K Sep 15 12:57  .
drwx------ 5 root root 4.0K Sep 15 12:57  ..
-rw------- 1 root root  60K Feb  8  2026  00017641453916470ada4f6b66654880.pdf
-rw------- 1 root root  182 Jul  2 12:13 '2026 Briefing: The Landscape of Free LLM APIs and Local Inference.gdoc'
-rw------- 1 root root 249K Feb 15  2026  22f29d23-312b-4ab3-a94c-a334c83bf888.pdf
-rw------- 1 root root 543K Oct 25  2023 'Aadhar (1).pdf'
-rw------- 1 root root 937K Jun 26  2024 'Aadhar Card .pdf'
-rw------- 1 root root 190K Jun 15  2021 'Aadhar Card.pdf'
-rw------- 1 root root 970K Jan 20  2024  Aadhar.pdf
-rw------- 1 root root  182 May 13 19:45 'Applied_Statistics_FAT_Checklist BY COLLEGE PREP.gsheet'
-rw------- 1 root root 2.4M Jun 21 19:49  C5EC1709-DA19-4682-BB30-3F4E3886346D.PNG
-rw------- 1 root root 1.3M Sep 18  2024 'CALCULATOR WARRANTY RECEPT .pdf'
-rw------- 1 root root  182 Mar  1  2026 'CARBON‑X (1).gslides'
-rw------- 1 root root  182 Feb 27  2026 'CARBON‑X (2).gslides'
-rw------- 1 root root  182 Feb 27  2026  CARBON-X.gslides
-rw------- 1 root root  182 Mar  1  2026  CARBON‑X.gslides
-rw------- 1 root root 249K Jun  9 12:35  Central_tendency_case_study_project_day_19.ipynb
-rw------- 1 root root  182 Aug 21 18:30 'CN_CAT1_Priority_Checklist  BY COLLEGE PREP .gsheet'
-rw------- 1 root root  182 May  3 06:56 'COA_FAT_Checklist by  COLLEGE PREP  (1).gsheet'
-rw------- 1 root root  182 May  6 02:21 'COA_FAT_Checklist by  COLLEGE PREP .gsheet'
-rw------- 1 root root 9.9K May  3 06:55 'COA_FAT_Checklist by  COLLEGE PREP .xlsx'
-rw------- 1 root root  182 May  3 06:54  COA_Module5_6_Checklist.gsheet
drwx------ 2 root root 4.0K Jul 13  2025 'Colab Notebooks'
-rw------- 1 root root  182 Apr 14 19:36 'Colleges and Documents Details.gsheet'
-rw------- 1 root root  182 Aug 26 04:14  Content_Refresh_Prioritization_Final_Paper_Extended.gdoc
-rw------- 1 root root  182 Aug 26 04:21  Content_Refresh_Prioritization_Final_Paper.gdoc
-rw------- 1 root root  182 Jun 14 04:36 'CoursePage_Plan_Short Summer-I  Semester 2025-26_ECE1003_ETH_AP2025266000133_Report_2026-06-14_10-04-19.gsheet'
-rw------- 1 root root  182 Aug  3 05:29 'CSE3004_Reference Material I (1).gslides'
-rw------- 1 root root  182 Aug  3 13:17 'CSE3004_Reference Material I.gslides'
-rw------- 1 root root  97K May 25  2025  d26c0f2708d14a7a97b5f82da0641fa3.pdf
-rw------- 1 root root  182 Aug 21 01:50 'DAA_CAT1_PRIORITY_CHECKLIST (1).gsheet'
-rw------- 1 root root  182 Aug 19 10:04  DAA_CAT1_PRIORITY_CHECKLIST.gsheet
-rw------- 1 root root 563K Jun 15  2021 'Date Of Birth Certificate.pdf'
-rw------- 1 root root  11K Mar 25 18:31 'DBMS_CAT2_CHECKLIST BY COLLEGE PREP.xlsx'
-rw------- 1 root root  182 Apr 17 15:27 'DBMS_Exam_Analysis (1).gsheet'
-rw------- 1 root root 6.3K Apr 17 15:17 'DBMS_Exam_Analysis (1).xlsx'
-rw------- 1 root root  182 Apr 17 15:04  DBMS_Exam_Analysis.gsheet
-rw------- 1 root root  182 May 11 12:03 'DBMS_FAT_CHECKLIST BY COLLEGE PREP.gsheet'
drwx------ 5 root root 4.0K Sep 15 12:57  DeepFake-Shield
drwx------ 2 root root 4.0K Sep 15 11:06 'DeepFake-Shield (1)'
-rw------- 1 root root  182 Aug 18 11:24 'Deep_Learning_CAT1_Priority_Checklist BY COLLEGE PREP.gsheet'
-rw------- 1 root root 174K Jun 20  2025 'Detailed Data Science RoadMap (1).pdf'
-rw------- 1 root root 198K Jun 20  2025 'Detailed Data Science RoadMap.pdf'
-rw------- 1 root root  182 Apr 10 13:55 'Digital Image Processing LAB Report .gdoc'
-rw------- 1 root root  182 Jul  4 07:06 'Digital Parametric Finance for Smallholder Agriculture: A Comprehensive Project Report.gdoc'
-rw------- 1 root root  12K May 13 12:08 'DIP_FAT_Checklist_With_Priority by college prep.xlsx'
drwx------ 2 root root 4.0K Dec 22  2025 'Documents '
-rw------- 1 root root  182 Jun 14 18:11  ECE1003_DIGITAL-LOGIC-DESIGN_ETH_1.1_3_ECE1003_revised.gdoc
-rw------- 1 root root  182 Mar 24 00:46 'ECE(COA)_CAT2_Checklist BY COLLEGEPREP.gsheet'
-rw------- 1 root root  33K Apr 26 06:39  EDA_Assignment_Day_14.ipynb
-rw------- 1 root root  78M Apr 29 15:54 'Entreprenuership VIdeo.mov'
-rw------- 1 root root 108K Aug 19  2023  EWS230802026659.pdf
-rw------- 1 root root 108K Oct 25  2023  Ews.pdf
-rw------- 1 root root  182 Aug 14 20:37 'Fall Semester 2026-27_CSE3004_ETH_AP2026272000671_2026-07-17_Reference-Material-I.gslides'
-rw------- 1 root root  182 Aug 15 10:21 'Fall Semester 2026-27_CSE3004_ETH_AP2026272000671_2026-07-24_Reference-Material-I.gslides'
-rw------- 1 root root  182 Aug 14 22:56 'Fall Semester 2026-27_CSE3004_ETH_AP2026272000671_2026-07-29_Reference-Material-I.gslides'
-rw------- 1 root root  837 Feb 15  2026  File_000.pdf
-rw------- 1 root root 6.2K Apr 14 18:46  Final_Study_Abroad_Tracker.xlsx
-rw------- 1 root root  182 Apr 14 18:33  Georgia_Masters_Tracker.gsheet
-rw------- 1 root root 6.3K Apr 14 18:34  Georgia_Masters_Visual.xlsx
drwx------ 2 root root 4.0K Feb 17  2026 'Google AI Studio'
drwx------ 2 root root 4.0K Jun 12  2025 'Mark Sheets'
-rw------- 1 root root 1.3M Aug 21  2023 'Marks Memo.pdf'
-rw------- 1 root root 307K Aug 23  2023 'MARKS MEMO.pdf'
-rw------- 1 root root  182 Mar 26 14:08  Math_Prep_Tracker.gsheet
-rw------- 1 root root  182 Mar 26 14:27 'Maths Checklist.gsheet'
-rw------- 1 root root 675K Apr 15 09:27  MediCore_HMS_SRS_v1.0.docx
-rw------- 1 root root 6.6K May 14 13:46  ML_FAT_Checklist_With_Priority.xlsx
-rw------- 1 root root 488K Jun 20  2025  mobilebasic
-rw------- 1 root root 151M Aug 16 05:39 'Module 1.pptx'
-rw------- 1 root root  45K Feb  8  2026  NOC_TBPL01-51126-4658866.pdf
-rw------- 1 root root  37K Apr 19 15:14  Numpy_Assignment_Day_10.ipynb
-rw------- 1 root root  182 Jul 10 10:46 'Operations Framework: The Dual-Reflex Methodology for Applied Machine Learning.gdoc'
-rw------- 1 root root  182 Aug 19 10:06 'OS_CAT1_Priority_Checklist  BY COLLEGE PREP.gsheet'
-rw------- 1 root root 263K Sep  1 06:07 'OS QUIZ-1 QUESTIONS.pdf'
-rw------- 1 root root  31K Apr 19 15:55  Pandas%20Assignment%20Day%2010.ipynb
-rw------- 1 root root 1.1M Aug 23  2023 'PASSPORT SIZE PHOTO (1).jpg'
-rw------- 1 root root 101K Dec 18  2024 'PASSPORT SIZE PHOTO.jpg'
-rw------- 1 root root  182 Aug 24 15:23  Ppt.gslides
-rw------- 1 root root 137K May 21 06:53 'Proforma 2.pdf'
-rw------- 1 root root 131K May 17 14:46  Proforma.pdf
-rw------- 1 root root 124M Jun  7 04:39 'Project Feedback Video'
-rw------- 1 root root  67K Apr 13 06:12  Python%20Basics%20Assignment%20Day%205.ipynb
-rw------- 1 root root  34K Apr 13 06:13  Python%20Data%20Structure%20Assignment%20Day%205.ipynb
-rw------- 1 root root 119K Jun 19 06:55 'Resume 1  (1).pdf'
-rw------- 1 root root  182 Sep  9 05:06 'Resume 1.gdoc'
-rw------- 1 root root 119K Jun 19 07:15 'Resume 1 .pdf'
-rw------- 1 root root  182 Jun 17 08:21  Resume.gdoc
-rw------- 1 root root  11K Mar 25 06:13 'SE_CAT2_Checklist_BY COLLEGE PREP.xlsx'
-rw------- 1 root root  182 Apr 14 18:46  Sheet.gsheet
-rw------- 1 root root 555K Aug 23  2023 'SIGNATURE (1).jpg'
-rw------- 1 root root 134K Nov  7  2023  SIGNATURE.jpg
-rw------- 1 root root  182 May  7 19:34 'Software_Engineering_FAT_Checklist_By COLLEGE PREP.gsheet'
-rw------- 1 root root  12K May  6 16:30 'Software_Engineering_FAT_Checklist_By COLLEGE PREP.xlsx'
-rw------- 1 root root  182 Apr 12 11:25 'Software Requirments System (SRS).gdoc'
-rw------- 1 root root  182 Mar 11  2026 'Software Testing .gslides'
-rw------- 1 root root  182 May 12 03:01 'STS Checklist.gsheet'
-rw------- 1 root root 280K Jun 11 07:26  Superstore_D23.ipynb
-rw------- 1 root root  182 Jul  8 13:22 'ThreatLens (1).gslides'
-rw------- 1 root root  182 Jul  8 13:39  ThreatLens.gslides
-rw------- 1 root root  17K Mar 17 19:47 'UAC Research Briefing.docx'
-rw------- 1 root root 1.4M May 22 02:40  UAC_Research_Paper.docx
-rw------- 1 root root  182 Aug 24 08:01 'Untitled document (1).gdoc'
-rw------- 1 root root  182 Jul  4 16:51 'Untitled document (2).gdoc'
-rw------- 1 root root  182 Sep 14 10:59 'Untitled document.gdoc'
-rw------- 1 root root  182 Mar 25 08:01 'Untitled spreadsheet (1).gsheet'
-rw------- 1 root root  182 May 14 13:50 'Untitled spreadsheet.gsheet'
-rw------- 1 root root  182 Feb 19  2026 'Vehicle Parking Management System (1).gslides'
-rw------- 1 root root  182 Feb 19  2026 'Vehicle Parking Management System.gslides'
-rw------- 1 root root  30K Apr 12 08:42  VPMS_SRS_v1.0.docx
-rw------- 1 root root 775K Apr 12 08:50  VPMS_SRS_v2.0_Full.docx
-rw------- 1 root root 5.3M Apr 29 16:53 'WhatsApp Video 2026-04-29 at 20.56.14.mp4'
-rw------- 1 root root  25K Mar 21 13:55 'Where Did My Money Go ?.docx'
-rw------- 1 root root  20K Mar 26 13:26 'where_did_my_money_go_project_paper (1).docx'
-rw------- 1 root root  20K Mar 21 13:32 'where_did_my_money_go_project_paper (2).docx'
-rw------- 1 root root  20K Mar 26 13:26  where_did_my_money_go_project_paper.docx
-rw------- 1 root root  182 Mar 11  2026 'White-Box Testing (1).gslides'
-rw------- 1 root root  182 Mar 11  2026 'White-Box Testing (2).gslides'
-rw------- 1 root root  182 Mar 11  2026 'White-Box Testing.gslides'

In [ ]:
!find "/content/drive/MyDrive/DeepFake-Shield" -maxdepth 4 -type d | head -50
!ls -lah "/content/drive/MyDrive/DeepFake-Shield"

/content/drive/MyDrive/DeepFake-Shield
/content/drive/MyDrive/DeepFake-Shield/datasets
/content/drive/MyDrive/DeepFake-Shield/datasets/raw
/content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real
/content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-Youtube-fake
/content/drive/MyDrive/DeepFake-Shield/datasets/raw/YouTube-real
/content/drive/MyDrive/DeepFake-Shield/artifacts
/content/drive/MyDrive/DeepFake-Shield/artifacts/splits
/content/drive/MyDrive/DeepFake-Shield/artifacts/experiments
/content/drive/MyDrive/DeepFake-Shield/artifacts/evaluation
/content/drive/MyDrive/DeepFake-Shield/artifacts/models
/content/drive/MyDrive/DeepFake-Shield/models
total 20K
drwx------ 5 root root 4.0K Sep 15 12:57 .
drwx------ 8 root root 4.0K Sep 15 12:57 ..
drwx------ 6 root root 4.0K Sep 15 11:08 artifacts
drwx------ 3 root root 4.0K Sep 15 11:05 datasets
drwx------ 2 root root 4.0K Sep 15 12:57 models

In [ ]:
!find "/content/drive/MyDrive/DeepFake-Shield" -type d \( -name "Celeb-Youtube-fake" -o -name "Celeb-real" -o -name "YouTube-real" \) 2>/dev/null

/content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real
/content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-Youtube-fake
/content/drive/MyDrive/DeepFake-Shield/datasets/raw/YouTube-real

In [ ]:
from pathlib import Path

# Repository
REPO_ROOT = Path("/content/deep-fake-shield")

# Dataset
DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")

# Existing splits
SPLITS_ROOT = REPO_ROOT / "artifacts/splits"

TRAIN_CSV = SPLITS_ROOT / "train.csv"
VAL_CSV   = SPLITS_ROOT / "val.csv"
TEST_CSV  = SPLITS_ROOT / "test.csv"

print("Repo:", REPO_ROOT)
print("Dataset:", DATA_ROOT)
print("Splits:", SPLITS_ROOT)

print("\nDataset exists:", DATA_ROOT.exists())
print("Train CSV:", TRAIN_CSV.exists())
print("Val CSV:", VAL_CSV.exists())
print("Test CSV:", TEST_CSV.exists())

Repo: /content/deep-fake-shield
Dataset: /content/drive/MyDrive/DeepFake-Shield/datasets/raw
Splits: /content/deep-fake-shield/artifacts/splits

Dataset exists: True
Train CSV: True
Val CSV: True
Test CSV: True

In [ ]:
print("Dataset exists:", DATA_ROOT.exists())

if not DATA_ROOT.exists():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_ROOT}"
    )

print("\nDataset folders:\n")

for folder in sorted(DATA_ROOT.iterdir()):

    if folder.is_dir():

        count = len(list(folder.rglob("*.mp4")))

        print(
            f"{folder.name}: {count}"
        )

Dataset exists: True

Dataset folders:

Celeb-Youtube-fake: 5299
Celeb-real: 482
YouTube-real: 230

Expected:

```text
Celeb-real: 482
Celeb-Youtube-fake: 5299
YouTube-real: 230
```

---

# CELL 7 — Count all videos

In [ ]:
VIDEO_EXTENSIONS = {
    ".mp4",
    ".avi",
    ".mov",
    ".mkv",
    ".webm"
}

videos = [
    p
    for p in DATA_ROOT.rglob("*")
    if p.is_file()
    and p.suffix.lower() in VIDEO_EXTENSIONS
]

print("Total labeled videos available:", len(videos))

Total labeled videos available: 6011

Expected:

```text
Total labeled videos available: 6011
```

---

# CELL 8 — Check the split files

In [ ]:
print("Train CSV:", TRAIN_CSV.exists())
print("Validation CSV:", VAL_CSV.exists())
print("Test CSV:", TEST_CSV.exists())

Train CSV: True
Validation CSV: True
Test CSV: True

All three should be:

```text
True
```

---

# CELL 9 — Inspect split sizes

In [ ]:
import pandas as pd

train_df = pd.read_csv(TRAIN_CSV)
val_df = pd.read_csv(VAL_CSV)
test_df = pd.read_csv(TEST_CSV)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

print(
    "\nTotal:",
    len(train_df) +
    len(val_df) +
    len(test_df)
)

Train: 4207
Validation: 902
Test: 902

Total: 6011

Expected:

```text
Train: 4207
Validation: 902
Test: 902

Total: 6011
```

**Do not recreate these splits.**

---

# CELL 10 — Inspect CSV structure

In [ ]:
print("Train columns:")
print(train_df.columns.tolist())

print("\nFirst 5 training rows:")
display(train_df.head())

Train columns:
['video_path', 'label', 'source', 'dataset', 'video_id', 'sha256']

First 5 training rows:

,video_path,label,source,dataset,video_id,sha256
0,/Users/gokulmallabathula/deep-fake/datasets/ra...,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:0,7062a11c8867b2bdef724a313412094511aa6b4ebe52a7...
1,/Users/gokulmallabathula/deep-fake/datasets/ra...,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1,06d003c71bc0b79702298416e55391f38495f45346e7d5...
2,/Users/gokulmallabathula/deep-fake/datasets/ra...,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:10,9e66998c0e0645a97ad112013eae9ae62244f7bbac4467...
3,/Users/gokulmallabathula/deep-fake/datasets/ra...,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1001,13964c2f76c78acda5769e7fae5ad4634d40d262fdec1a...
4,/Users/gokulmallabathula/deep-fake/datasets/ra...,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1002,ba39d9b2c7581156222c350ea24c2ed03fdd07bebc6cdd...

This is important because the model script needs to know where the video path and label are stored.

---

# CELL 11 — Inspect training script arguments

In [ ]:
%cd /content/deep-fake-shield

!python scripts/train_baseline.py --help

/content/deep-fake-shield
usage: train_baseline.py [-h] [--train-csv TRAIN_CSV] [--val-csv VAL_CSV]
                         [--video-root VIDEO_ROOT] [--epochs EPOCHS]
                         [--limit LIMIT] [--frames-per-video FRAMES_PER_VIDEO]
                         [--batch-size BATCH_SIZE] [--workers WORKERS]
                         [--output-dir OUTPUT_DIR] [--pretrained]
                         [--seed SEED]

Train a small, reproducible EfficientNet face/frame baseline.

options:
  -h, --help            show this help message and exit
  --train-csv TRAIN_CSV
  --val-csv VAL_CSV
  --video-root VIDEO_ROOT
                        Mounted dataset root containing the raw dataset
                        folders
  --epochs EPOCHS
  --limit LIMIT         Limit each split for a sanity run; 0 means all rows
  --frames-per-video FRAMES_PER_VIDEO
  --batch-size BATCH_SIZE
  --workers WORKERS
  --output-dir OUTPUT_DIR
  --pretrained
  --seed SEED

You should see the arguments you were using previously, including:

```text
--train-csv
--val-csv
--video-root
--pretrained
--epochs
--limit
--frames-per-video
--batch-size
--workers
--output-dir
```

---

# CELL 12 — Inspect evaluation arguments

In [ ]:
!python scripts/evaluate_baseline.py --help

usage: evaluate_baseline.py [-h] [--csv CSV] [--video-root VIDEO_ROOT]
                            --checkpoint CHECKPOINT [--output-dir OUTPUT_DIR]
                            [--frames FRAMES] [--limit LIMIT]

Evaluate a frame baseline at video level on a held-out split.

options:
  -h, --help            show this help message and exit
  --csv CSV
  --video-root VIDEO_ROOT
                        Mounted dataset root containing the raw dataset
                        folders
  --checkpoint CHECKPOINT
  --output-dir OUTPUT_DIR
  --frames FRAMES
  --limit LIMIT

---

# CELL 13 — Inspect inference arguments

In [ ]:
!python scripts/infer_video.py --help

usage: infer_video.py [-h] --video VIDEO --checkpoint CHECKPOINT
                      [--frames FRAMES] [--output OUTPUT]

Analyze one video with a trained EfficientNet baseline.

options:
  -h, --help            show this help message and exit
  --video VIDEO
  --checkpoint CHECKPOINT
  --frames FRAMES
  --output OUTPUT

---

# CELL 14 — Check class distribution

First let's determine the label column automatically.

In [ ]:
print("Train columns:", train_df.columns.tolist())

Train columns: ['video_path', 'label', 'source', 'dataset', 'video_id', 'sha256']

Then run:

In [ ]:
for col in train_df.columns:
    print(
        f"\nColumn: {col}"
    )

    try:
        print(
            train_df[col].value_counts().head(10)
        )
    except:
        pass

Column: video_path
video_path
/Users/gokulmallabathula/deep-fake/datasets/raw/YouTube-real/99.mp4            1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/0.mp4       1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1.mp4       1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/10.mp4      1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1001.mp4    1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1002.mp4    1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1003.mp4    1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1004.mp4    1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1006.mp4    1
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1007.mp4    1
Name: count, dtype: int64

Column: label
label
1    3709
0     498
Name: count, dtype: int64

Column: source
Series([], Name: count, dtype: int64)

Column: dataset
dataset
Celeb-Youtube-fake    3709
Celeb-real             352
YouTube-real           146
Name: count, dtype: int64

Column: video_id
video_id
YouTube-real:99            1
Celeb-Youtube-fake:0       1
Celeb-Youtube-fake:1       1
Celeb-Youtube-fake:10      1
Celeb-Youtube-fake:1001    1
Celeb-Youtube-fake:1002    1
Celeb-Youtube-fake:1003    1
Celeb-Youtube-fake:1004    1
Celeb-Youtube-fake:1006    1
Celeb-Youtube-fake:1007    1
Name: count, dtype: int64

Column: sha256
sha256
cdddddda2c42ac957c551126f20afbe7636cadf4cae224ea7973ca07cb845ad4    1
7062a11c8867b2bdef724a313412094511aa6b4ebe52a792a9a07deb0ecec6cf    1
06d003c71bc0b79702298416e55391f38495f45346e7d576435a5418d251da10    1
9e66998c0e0645a97ad112013eae9ae62244f7bbac4467d16bcf7747636e8e63    1
13964c2f76c78acda5769e7fae5ad4634d40d262fdec1a8e3939dfe018189f65    1
ba39d9b2c7581156222c350ea24c2ed03fdd07bebc6cdd9331379d1368c17fc5    1
a5d90f3c0e69a23dd4aede6ba5b15a35ebb5a6fc57e4b783b4aae59e9063eb7f    1
a5be914f197b8ccd93411899f5188ecdc6e8fb8c86324e58b6d86e14f493adc8    1
994839b566b0ed7ceacdac6f078d9f17e5cedf54ea227aa7001d42b00ee9e8a9    1
510cbea2d38af8b14a999a16ad788ce77fce8da0bbea3f4d5b4814cf77c283f7    1
Name: count, dtype: int64

We need to identify the column containing `real/fake` or `0/1`.

---

# CELL 15 — Verify paths inside the CSV

This is extremely important because the CSVs were originally created on your Mac.

In [ ]:
print(train_df.head(10).to_string(index=False))

                                                                 video_path  label  source            dataset                video_id                                                           sha256
   /Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/0.mp4      1     NaN Celeb-Youtube-fake    Celeb-Youtube-fake:0 7062a11c8867b2bdef724a313412094511aa6b4ebe52a792a9a07deb0ecec6cf
   /Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1.mp4      1     NaN Celeb-Youtube-fake    Celeb-Youtube-fake:1 06d003c71bc0b79702298416e55391f38495f45346e7d576435a5418d251da10
  /Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/10.mp4      1     NaN Celeb-Youtube-fake   Celeb-Youtube-fake:10 9e66998c0e0645a97ad112013eae9ae62244f7bbac4467d16bcf7747636e8e63
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1001.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1001 13964c2f76c78acda5769e7fae5ad4634d40d262fdec1a8e3939dfe018189f65
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1002.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1002 ba39d9b2c7581156222c350ea24c2ed03fdd07bebc6cdd9331379d1368c17fc5
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1003.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1003 a5d90f3c0e69a23dd4aede6ba5b15a35ebb5a6fc57e4b783b4aae59e9063eb7f
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1004.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1004 a5be914f197b8ccd93411899f5188ecdc6e8fb8c86324e58b6d86e14f493adc8
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1006.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1006 994839b566b0ed7ceacdac6f078d9f17e5cedf54ea227aa7001d42b00ee9e8a9
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1007.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1007 510cbea2d38af8b14a999a16ad788ce77fce8da0bbea3f4d5b4814cf77c283f7
/Users/gokulmallabathula/deep-fake/datasets/raw/Celeb-Youtube-fake/1008.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1008 b6e86d15f2932767aecccf696d69e199fc1f4bba132df26c4f5e82185931ac1a

If your CSV contains something like:

```text
datasets/raw/Celeb-Youtube-fake/100.mp4
```

that's good.

If it contains:

```text
/Users/gokulmallabathula/deep-fake/datasets/raw/...
```

that's a problem and we'll convert it.

# Fix: Clean Mac paths in CSVs

In [ ]:
# Function to clean video paths
def clean_mac_path(path_series):
    # This assumes the unwanted part is always '/Users/gokulmallabathula/deep-fake/'
    # and the desired relative path starts after 'datasets/raw/'
    # The DATA_ROOT already includes 'datasets/raw'
    return path_series.apply(lambda p: p.replace('/Users/gokulmallabathula/deep-fake/', ''))

# Apply the cleaning function to all relevant DataFrames
train_df['video_path'] = clean_mac_path(train_df['video_path'])
val_df['video_path'] = clean_mac_path(val_df['video_path'])
test_df['video_path'] = clean_mac_path(test_df['video_path'])

print("Cleaned paths in train_df:")
display(train_df.head())

print("\nFirst 10 training rows after cleaning:")
print(train_df.head(10).to_string(index=False))

Cleaned paths in train_df:

,video_path,label,source,dataset,video_id,sha256
0,datasets/raw/Celeb-Youtube-fake/0.mp4,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:0,7062a11c8867b2bdef724a313412094511aa6b4ebe52a7...
1,datasets/raw/Celeb-Youtube-fake/1.mp4,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1,06d003c71bc0b79702298416e55391f38495f45346e7d5...
2,datasets/raw/Celeb-Youtube-fake/10.mp4,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:10,9e66998c0e0645a97ad112013eae9ae62244f7bbac4467...
3,datasets/raw/Celeb-Youtube-fake/1001.mp4,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1001,13964c2f76c78acda5769e7fae5ad4634d40d262fdec1a...
4,datasets/raw/Celeb-Youtube-fake/1002.mp4,1,NaN,Celeb-Youtube-fake,Celeb-Youtube-fake:1002,ba39d9b2c7581156222c350ea24c2ed03fdd07bebc6cdd...

First 10 training rows after cleaning:
                              video_path  label  source            dataset                video_id                                                           sha256
   datasets/raw/Celeb-Youtube-fake/0.mp4      1     NaN Celeb-Youtube-fake    Celeb-Youtube-fake:0 7062a11c8867b2bdef724a313412094511aa6b4ebe52a792a9a07deb0ecec6cf
   datasets/raw/Celeb-Youtube-fake/1.mp4      1     NaN Celeb-Youtube-fake    Celeb-Youtube-fake:1 06d003c71bc0b79702298416e55391f38495f45346e7d576435a5418d251da10
  datasets/raw/Celeb-Youtube-fake/10.mp4      1     NaN Celeb-Youtube-fake   Celeb-Youtube-fake:10 9e66998c0e0645a97ad112013eae9ae62244f7bbac4467d16bcf7747636e8e63
datasets/raw/Celeb-Youtube-fake/1001.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1001 13964c2f76c78acda5769e7fae5ad4634d40d262fdec1a8e3939dfe018189f65
datasets/raw/Celeb-Youtube-fake/1002.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1002 ba39d9b2c7581156222c350ea24c2ed03fdd07bebc6cdd9331379d1368c17fc5
datasets/raw/Celeb-Youtube-fake/1003.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1003 a5d90f3c0e69a23dd4aede6ba5b15a35ebb5a6fc57e4b783b4aae59e9063eb7f
datasets/raw/Celeb-Youtube-fake/1004.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1004 a5be914f197b8ccd93411899f5188ecdc6e8fb8c86324e58b6d86e14f493adc8
datasets/raw/Celeb-Youtube-fake/1006.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1006 994839b566b0ed7ceacdac6f078d9f17e5cedf54ea227aa7001d42b00ee9e8a9
datasets/raw/Celeb-Youtube-fake/1007.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1007 510cbea2d38af8b14a999a16ad788ce77fce8da0bbea3f4d5b4814cf77c283f7
datasets/raw/Celeb-Youtube-fake/1008.mp4      1     NaN Celeb-Youtube-fake Celeb-Youtube-fake:1008 b6e86d15f2932767aecccf696d69e199fc1f4bba132df26c4f5e82185931ac1a

---

# CELL 16 — Test one CSV video against Drive

In [ ]:
from pathlib import Path

# Show every value from the first row
first_row = train_df.iloc[0]

print(first_row)

video_path                datasets/raw/Celeb-Youtube-fake/0.mp4
label                                                         1
source                                                      NaN
dataset                                      Celeb-Youtube-fake
video_id                                   Celeb-Youtube-fake:0
sha256        7062a11c8867b2bdef724a313412094511aa6b4ebe52a7...
Name: 0, dtype: object

In [ ]:
for col in train_df.columns:
    print(col, "=", first_row[col])

video_path = datasets/raw/Celeb-Youtube-fake/0.mp4
label = 1
source = nan
dataset = Celeb-Youtube-fake
video_id = Celeb-Youtube-fake:0
sha256 = 7062a11c8867b2bdef724a313412094511aa6b4ebe52a792a9a07deb0ecec6cf

This tells us the exact video path format.

---

# CELL 17 — Make sure we are in the repository

In [ ]:
%cd /content/deep-fake-shield

print("Current directory:")
!pwd

/content/deep-fake-shield
Current directory:
/content/deep-fake-shield

Expected:

```text
/content/deep-fake-shield
```

---

# CELL 18 — Run the existing dataset audit

**Do this for project verification only.**

In [ ]:
!python scripts/inspect_dataset.py

{
  "dataset_root": "/content/deep-fake-shield/datasets/raw",
  "total_videos": 0,
  "readable_videos": 0,
  "corrupted_or_unreadable_videos": 0,
  "class_distribution": {},
  "videos_by_dataset": {},
  "videos_by_extension": {},
  "duration_seconds": {
    "average": null,
    "minimum": null,
    "maximum": null
  },
  "average_fps": null,
  "resolution_distribution": {},
  "source_grouping": {
    "available": false,
    "reason": "The dataset is flat and contains no identity/source metadata or source subdirectories."
  }
}
Duplicate filenames: 0
Duplicate hashes: 0
Report: /content/deep-fake-shield/artifacts/dataset_report.json

If it reports:

```text
total_videos: 0
```

**that's expected with your current script**, because that script defaults to:

```text
/content/deep-fake-shield/datasets/raw
```

while your real dataset is in Drive.

Don't let that stop us. Our training command will explicitly provide the correct dataset path.

---

# CELL 19 — Create experiment directory

In [ ]:
SUBMISSION_DIR = (
    REPO_ROOT
    / "artifacts"
    / "experiments"
    / "submission_v1"
)

SUBMISSION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(SUBMISSION_DIR)

/content/deep-fake-shield/artifacts/experiments/submission_v1

---

# CELL 20 — GPU sanity test

In [ ]:
import torch
import time

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

if device.type == "cuda":

    x = torch.randn(
        32,
        3,
        224,
        224,
        device=device
    )

    start = time.time()

    for _ in range(100):
        y = x * 2.0

    torch.cuda.synchronize()

    elapsed = time.time() - start

    print(
        "GPU test completed in:",
        round(elapsed, 3),
        "seconds"
    )

Device: cuda
GPU test completed in: 0.052 seconds

---

# 🚨 CELL 21 — 100-video sanity training

**Do this before full training.**

In [ ]:
import cv2

print("OpenCV version:", getattr(cv2, "__version__", "unknown"))
print("cv2 location:", getattr(cv2, "__file__", "unknown"))
print("Has CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))

OpenCV version: 5.0.0
cv2 location: /usr/local/lib/python3.13/dist-packages/cv2/__init__.py
Has CascadeClassifier: False

In [ ]:
!pip uninstall -y opencv-python opencv-python-headless opencv-contrib-python opencv-contrib-python-headless

Found existing installation: opencv-python 5.0.0.93
Uninstalling opencv-python-5.0.0.93:
  Successfully uninstalled opencv-python-5.0.0.93
Found existing installation: opencv-python-headless 5.0.0.93
Uninstalling opencv-python-headless-5.0.0.93:
  Successfully uninstalled opencv-python-headless-5.0.0.93
Found existing installation: opencv-contrib-python 4.14.0.94
Uninstalling opencv-contrib-python-4.14.0.94:
  Successfully uninstalled opencv-contrib-python-4.14.0.94
WARNING: Skipping opencv-contrib-python-headless as it is not installed.

In [ ]:
!pip install -q --no-cache-dir opencv-python-headless==4.10.0.84

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 MB 220.8 MB/s eta 0:00:00

In [ ]:
%cd /content/deep-fake-shield

!python scripts/train_baseline.py \
    --train-csv artifacts/splits/train.csv \
    --val-csv artifacts/splits/val.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --pretrained \
    --epochs 1 \
    --limit 100 \
    --frames-per-video 2 \
    --batch-size 8 \
    --workers 2 \
    --output-dir artifacts/experiments/colab_sanity_001

/content/deep-fake-shield
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth
100% 20.5M/20.5M [00:00<00:00, 154MB/s]
Traceback (most recent call last):
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 113, in <module>
    raise SystemExit(main())
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 96, in main
    val_metrics = run_epoch(model, val_loader, device)
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 30, in run_epoch
    for frames, targets in loader:
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 741, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1524, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1483, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1310, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.13/multiprocessing/queues.py", line 111, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 445, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 1174, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.13/selectors.py", line 398, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

In [ ]:
import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

In [ ]:
!nvidia-smi

Tue Sep 15 13:18:46 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P0             30W /   70W |     183MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1499      C   /usr/bin/python3                        180MiB |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Selected device:", device)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

PyTorch: 2.11.0+cu128
CUDA available: True
CUDA version: 12.8
Selected device: cuda
GPU: Tesla T4

In [ ]:
from pathlib import Path

DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")

for folder in ["Celeb-Youtube-fake", "Celeb-real", "YouTube-real"]:
    videos = list((DATA_ROOT / folder).glob("*.mp4"))
    print(folder, len(videos))

    if videos:
        print("Example:", videos[0])

Celeb-Youtube-fake 5299
Example: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-Youtube-fake/4866.mp4
Celeb-real 482
Example: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real/1.mp4
YouTube-real 230
Example: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/YouTube-real/0.mp4

In [ ]:
import cv2

video_path = list((DATA_ROOT / "Celeb-real").glob("*.mp4"))[0]

cap = cv2.VideoCapture(str(video_path))

print("Video:", video_path)
print("Opened:", cap.isOpened())
print("Frame count:", int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
print("FPS:", cap.get(cv2.CAP_PROP_FPS))

ret, frame = cap.read()

print("First frame read:", ret)
print("Frame shape:", frame.shape if ret else None)

cap.release()

Video: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real/1.mp4
Opened: True
Frame count: 350
FPS: 30.0
First frame read: True
Frame shape: (500, 942, 3)

In [ ]:
!pip uninstall -y opencv-python opencv-python-headless opencv-contrib-python opencv-contrib-python-headless

WARNING: Skipping opencv-python as it is not installed.
Found existing installation: opencv-python-headless 4.10.0.84
Uninstalling opencv-python-headless-4.10.0.84:
  Successfully uninstalled opencv-python-headless-4.10.0.84
WARNING: Skipping opencv-contrib-python as it is not installed.
WARNING: Skipping opencv-contrib-python-headless as it is not installed.

In [ ]:
!pip list | grep -i opencv

In [ ]:
!pip install --no-cache-dir --force-reinstall opencv-contrib-python-headless==4.11.0.86

Collecting opencv-contrib-python-headless==4.11.0.86
  Downloading opencv_contrib_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.21.2 (from opencv-contrib-python-headless==4.11.0.86)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Downloading opencv_contrib_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (56.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 MB 245.9 MB/s eta 0:00:00
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 242.3 MB/s eta 0:00:00
Installing collected packages: numpy, opencv-contrib-python-headless
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires opencv-python>=3.4.8.29, which is not installed.
albumentations 2.0.8 requires opencv-python-headless>=4.9.0.80, which is not installed.
albucore 0.0.24 requires opencv-python-headless>=4.9.0.80, which is not installed.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.3 which is incompatible.
Successfully installed numpy-2.5.3 opencv-contrib-python-headless-4.11.0.86

In [ ]:
import sys

sys.path.insert(0, "/content/deep-fake-shield")

from ml.data.video_dataset import FaceCropper

cropper = FaceCropper()

print("FaceCropper initialized successfully.")
print("Detector empty:", cropper.detector.empty())

FaceCropper initialized successfully.
Detector empty: False

### What we want

The script should:

```text
Load pretrained model
        ↓
Load videos
        ↓
Extract frames
        ↓
Train
        ↓
Validate
        ↓
Save checkpoint
```

---

# CELL 22 — Check checkpoint

In [ ]:
from pathlib import Path

# Repository
REPO_ROOT = Path("/content/deep-fake-shield")

# Dataset on Google Drive
DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")

# Existing dataset splits
SPLITS_ROOT = REPO_ROOT / "artifacts" / "splits"

TRAIN_CSV = SPLITS_ROOT / "train.csv"
VAL_CSV = SPLITS_ROOT / "val.csv"
TEST_CSV = SPLITS_ROOT / "test.csv"

print("Repository exists:", REPO_ROOT.exists())
print("Dataset exists:", DATA_ROOT.exists())
print("Splits exists:", SPLITS_ROOT.exists())
print("Train CSV:", TRAIN_CSV.exists())
print("Val CSV:", VAL_CSV.exists())
print("Test CSV:", TEST_CSV.exists())

Repository exists: True
Dataset exists: True
Splits exists: True
Train CSV: True
Val CSV: True
Test CSV: True

In [ ]:
from pathlib import Path

SANITY_DIR = (
    REPO_ROOT
    / "artifacts"
    / "experiments"
    / "colab_sanity_001"
)

print("Experiment exists:", SANITY_DIR.exists())

if SANITY_DIR.exists():

    print("\nFiles:")

    for item in SANITY_DIR.iterdir():
        print(
            "📄",
            item.name
        )

Experiment exists: True

Files:

Look for:

```text
best_model.pt
```

---

# CELL 23 — Evaluate sanity model

In [ ]:
%cd /content/deep-fake-shield

/content/deep-fake-shield

In [ ]:
%cd /content/deep-fake-shield

!find artifacts -type f \( -name "*.pt" -o -name "*.pth" -o -name "*.ckpt" \) -print

/content/deep-fake-shield

In [ ]:
!find artifacts/experiments -maxdepth 2 -type d -print

artifacts/experiments
artifacts/experiments/colab_sanity_001
artifacts/experiments/submission_v1

In [ ]:
%cd /content/deep-fake-shield
!find artifacts -type f \( -name "*.pt" -o -name "*.pth" -o -name "*.ckpt" \) -print

/content/deep-fake-shield

In [ ]:
import torch
import cv2

print("GPU:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")
print("OpenCV:", cv2.__version__)
print("CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))

GPU: True
Device: Tesla T4
OpenCV: 4.11.0
CascadeClassifier: True

In [ ]:
%cd /content/deep-fake-shield

!python scripts/train_baseline.py \
    --train-csv artifacts/splits/train.csv \
    --val-csv artifacts/splits/val.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --pretrained \
    --epochs 1 \
    --limit 100 \
    --frames-per-video 2 \
    --batch-size 8 \
    --workers 2 \
    --output-dir artifacts/experiments/colab_sanity_001

/content/deep-fake-shield
{
  "epoch": 1,
  "train": {
    "accuracy": 0.73,
    "precision": 0.9259259259259259,
    "recall": 0.5,
    "f1": 0.6493506493506493,
    "roc_auc": 0.7792000000000001,
    "pr_auc": 0.8317532453854263,
    "false_positive_rate": 0.04,
    "false_negative_rate": 0.5,
    "support": 100,
    "loss": 0.6282301926612854
  },
  "validation": {
    "accuracy": 0.56,
    "precision": 0.7142857142857143,
    "recall": 0.2,
    "f1": 0.3125,
    "roc_auc": 0.598,
    "pr_auc": 0.6413366125280481,
    "false_positive_rate": 0.08,
    "false_negative_rate": 0.8,
    "support": 100,
    "loss": 0.693071894645691
  }
}
device=cuda output=artifacts/experiments/colab_sanity_001

In [ ]:
if SANITY_DIR.exists():

    !python scripts/evaluate_baseline.py \
        --csv artifacts/splits/test.csv \
        --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
        --checkpoint artifacts/experiments/colab_sanity_001/best_model.pt \
        --frames 2 \
        --limit 100 \
        --output-dir artifacts/evaluation/colab_sanity_001

{
  "device": "cuda",
  "videos": 100,
  "metrics": {
    "accuracy": 0.57,
    "precision": 0.7058823529411765,
    "recall": 0.24,
    "f1": 0.3582089552238806,
    "roc_auc": 0.6316,
    "pr_auc": 0.6444281831306727,
    "false_positive_rate": 0.1,
    "false_negative_rate": 0.76,
    "support": 100
  }
}

---

# CELL 24 — Read sanity metrics

In [ ]:
import json

metrics_file = (
    REPO_ROOT
    / "artifacts"
    / "evaluation"
    / "colab_sanity_001"
    / "test_metrics.json"
)

if metrics_file.exists():

    metrics = json.loads(
        metrics_file.read_text()
    )

    print(
        json.dumps(
            metrics,
            indent=2
        )
    )

else:
    print(
        "Metrics file not found:",
        metrics_file
    )

{
  "accuracy": 0.57,
  "precision": 0.7058823529411765,
  "recall": 0.24,
  "f1": 0.3582089552238806,
  "roc_auc": 0.6316,
  "pr_auc": 0.6444281831306727,
  "false_positive_rate": 0.1,
  "false_negative_rate": 0.76,
  "support": 100
}

This sanity run is only to prove the pipeline works.

**Don't worry if the metrics are poor on 100 videos.**

---

# 🚀 CELL 25 — FULL TRAINING

If Cell 21 completed successfully and produced a checkpoint, now we do the real training.

In [ ]:
if SANITY_DIR.exists() and (SANITY_DIR / "best_model.pt").exists():
    %cd /content/deep-fake-shield

    !python scripts/train_baseline.py \
        --train-csv artifacts/splits/train.csv \
        --val-csv artifacts/splits/val.csv \
        --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
        --pretrained \
        --epochs 5 \
        --limit 0 \
        --frames-per-video 4 \
        --batch-size 8 \
        --workers 2 \
        --output-dir artifacts/experiments/submission_v1
else:
    print("Sanity training not completed or best_model.pt not found. Please check Cell 21.")

/content/deep-fake-shield
Traceback (most recent call last):
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 113, in <module>
    raise SystemExit(main())
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 95, in main
    train_metrics = run_epoch(model, train_loader, device, optimizer)
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 30, in run_epoch
    for frames, targets in loader:
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 741, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1524, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1483, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1310, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.13/multiprocessing/queues.py", line 111, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 445, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.13/multiprocessing/connection.py", line 1174, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.13/selectors.py", line 398, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

In [ ]:
%cd /content/deep-fake-shield

!find artifacts/experiments/submission_v1 -maxdepth 2 -type f -print 2>/dev/null

/content/deep-fake-shield

In [ ]:
%cd /content/deep-fake-shield

!python scripts/train_baseline.py \
    --train-csv artifacts/splits/train.csv \
    --val-csv artifacts/splits/val.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --pretrained \
    --epochs 2 \
    --limit 1000 \
    --frames-per-video 2 \
    --batch-size 16 \
    --workers 2 \
    --output-dir artifacts/experiments/submission_fast

/content/deep-fake-shield
Traceback (most recent call last):
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 113, in <module>
    raise SystemExit(main())
                     ~~~~^^
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 95, in main
    train_metrics = run_epoch(model, train_loader, device, optimizer)
  File "/content/deep-fake-shield/scripts/train_baseline.py", line 34, in run_epoch
    logits = model(frames.reshape(batch * steps, channels, height, width))
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/torchvision/models/efficientnet.py", line 344, in forward
    return self._forward_impl(x)
           ~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/dist-packages/torchvision/models/efficientnet.py", line 339, in _forward_impl
    x = self.classifier(x)
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/container.py", line 253, in forward
    input = module(input)
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/modules/dropout.py", line 73, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/torch/nn/functional.py", line 1443, in dropout
    _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
                                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

In [ ]:
!nvidia-smi

Tue Sep 15 13:41:07 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P0             30W /   70W |       3MiB /  15360MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
%cd /content/deep-fake-shield

!find artifacts/experiments/submission_v1 -maxdepth 2 -type f -print 2>/dev/null

/content/deep-fake-shield

In [ ]:
!find artifacts/experiments -maxdepth 2 -type f \( -name "*.pt" -o -name "*.json" -o -name "*.csv" \) -print

artifacts/experiments/colab_sanity_001/last_model.pt
artifacts/experiments/colab_sanity_001/best_model.pt
artifacts/experiments/colab_sanity_001/config.json
artifacts/experiments/colab_sanity_001/training_history.json

In [ ]:
import json
from pathlib import Path

history_file = Path(
    "/content/deep-fake-shield/artifacts/experiments/colab_sanity_001/training_history.json"
)

with open(history_file) as f:
    history = json.load(f)

print(json.dumps(history, indent=2))

[
  {
    "epoch": 1,
    "train": {
      "accuracy": 0.73,
      "precision": 0.9259259259259259,
      "recall": 0.5,
      "f1": 0.6493506493506493,
      "roc_auc": 0.7792000000000001,
      "pr_auc": 0.8317532453854263,
      "false_positive_rate": 0.04,
      "false_negative_rate": 0.5,
      "support": 100,
      "loss": 0.6282301926612854
    },
    "validation": {
      "accuracy": 0.56,
      "precision": 0.7142857142857143,
      "recall": 0.2,
      "f1": 0.3125,
      "roc_auc": 0.598,
      "pr_auc": 0.6413366125280481,
      "false_positive_rate": 0.08,
      "false_negative_rate": 0.8,
      "support": 100,
      "loss": 0.693071894645691
    }
  }
]

In [ ]:
config_file = Path(
    "/content/deep-fake-shield/artifacts/experiments/colab_sanity_001/config.json"
)

with open(config_file) as f:
    config = json.load(f)

print(json.dumps(config, indent=2))

{
  "train_csv": "artifacts/splits/train.csv",
  "val_csv": "artifacts/splits/val.csv",
  "video_root": "/content/drive/MyDrive/DeepFake-Shield/datasets/raw",
  "epochs": 1,
  "limit": 100,
  "frames_per_video": 2,
  "batch_size": 8,
  "workers": 2,
  "output_dir": "artifacts/experiments/colab_sanity_001",
  "pretrained": true,
  "seed": 42
}

In [ ]:
!ls -lh artifacts/experiments/colab_sanity_001/*.pt

-rw-r--r-- 1 root root 16M Sep 15 13:25 artifacts/experiments/colab_sanity_001/best_model.pt
-rw-r--r-- 1 root root 16M Sep 15 13:25 artifacts/experiments/colab_sanity_001/last_model.pt

In [ ]:
%cd /content/deep-fake-shield

!python scripts/evaluate_baseline.py \
    --csv artifacts/splits/test.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --checkpoint artifacts/experiments/colab_sanity_001/best_model.pt \
    --frames 2 \
    --limit 100 \
    --output-dir artifacts/evaluation/colab_sanity_001

/content/deep-fake-shield
{
  "device": "cuda",
  "videos": 100,
  "metrics": {
    "accuracy": 0.57,
    "precision": 0.7058823529411765,
    "recall": 0.24,
    "f1": 0.3582089552238806,
    "roc_auc": 0.6316,
    "pr_auc": 0.6444281831306727,
    "false_positive_rate": 0.1,
    "false_negative_rate": 0.76,
    "support": 100
  }
}

In [ ]:
!nvidia-smi

Tue Sep 15 13:44:24 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch
import cv2

print("PyTorch CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("OpenCV:", cv2.__version__)
print("CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))

PyTorch CUDA: True
GPU: Tesla T4
OpenCV: 4.11.0
CascadeClassifier: True

In [ ]:
from pathlib import Path

DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")

videos = list((DATA_ROOT / "Celeb-real").glob("*.mp4"))

print("Videos found:", len(videos))
print("Testing:", videos[0])

Videos found: 482
Testing: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real/1.mp4

In [ ]:
from pathlib import Path
import sys
import time

sys.path.insert(0, "/content/deep-fake-shield")

from ml.data.video_dataset import VideoFrameDataset

REPO_ROOT = Path("/content/deep-fake-shield")
DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")
TRAIN_CSV = REPO_ROOT / "artifacts/splits/train.csv"

start = time.time()

dataset = VideoFrameDataset(
    TRAIN_CSV,                 # Path object, NOT string
    frames_per_video=2,
    transform=None,
    video_root=DATA_ROOT
)

print("Dataset initialized in:", time.time() - start, "seconds")
print("Dataset length:", len(dataset))

Dataset initialized in: 0.03896594047546387 seconds
Dataset length: 4207

In [ ]:
%cd /content/deep-fake-shield

!sed -n '1,150p' ml/data/video_dataset.py

/content/deep-fake-shield
"""Lazy video-frame dataset with deterministic sampling and face crops."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import torch
from PIL import Image
from torch.utils.data import Dataset


def sample_frame_indices(frame_count: int, count: int) -> np.ndarray:
    if frame_count <= 0:
        return np.zeros(count, dtype=np.int64)
    return np.linspace(0, max(frame_count - 1, 0), count, dtype=np.int64)


class FaceCropper:
    def __init__(self, margin: float = 0.2) -> None:
        self.margin = margin
        cascade_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
        self.detector = cv2.CascadeClassifier(cascade_path)

    def crop(self, frame: np.ndarray) -> np.ndarray | None:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = self.detector.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(32, 32))
        if len(faces) == 0:
            return None
        x, y, width, height = max(faces, key=lambda box: int(box[2]) * int(box[3]))
        pad_x, pad_y = int(width * self.margin), int(height * self.margin)
        top, bottom = max(0, y - pad_y), min(frame.shape[0], y + height + pad_y)
        left, right = max(0, x - pad_x), min(frame.shape[1], x + width + pad_x)
        return frame[top:bottom, left:right]


class VideoFrameDataset(Dataset[tuple[torch.Tensor, torch.Tensor]]):
    def __init__(self, csv_path: Path, frames_per_video: int = 4, transform: Any = None, video_root: Path | None = None) -> None:
        with csv_path.open(newline="", encoding="utf-8") as csv_file:
            self.records = list(csv.DictReader(csv_file))
        self.frames_per_video = frames_per_video
        self.transform = transform
        self.video_root = video_root
        self.cropper = FaceCropper()

    def resolve_video_path(self, path: str) -> Path:
        original = Path(path)
        if original.exists() or self.video_root is None:
            return original
        marker = Path("datasets/raw")
        try:
            relative = Path(*original.parts[original.parts.index(marker.parts[0]) :])
            marker_index = next(index for index in range(len(original.parts) - 1) if Path(*original.parts[index : index + 2]) == marker)
            relative = Path(*original.parts[marker_index + len(marker.parts) :])
            candidate = self.video_root / relative
            if candidate.exists():
                return candidate
        except (ValueError, StopIteration):
            pass
        candidate = self.video_root / original.name
        return candidate if candidate.exists() else original

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        record = self.records[index]
        capture = cv2.VideoCapture(str(self.resolve_video_path(record["video_path"])))
        frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        frames = []
        for frame_index in sample_frame_indices(frame_count, self.frames_per_video):
            capture.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            ok, frame = capture.read()
            if not ok:
                continue
            crop = self.cropper.crop(frame)
            image = crop if crop is not None else frame
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            frames.append(Image.fromarray(image))
        capture.release()
        if not frames:
            frames = [Image.fromarray(np.zeros((224, 224, 3), dtype=np.uint8))]
        if self.transform is not None:
            tensors = [self.transform(frame) for frame in frames]
        else:
            tensors = [torch.from_numpy(np.asarray(frame)).permute(2, 0, 1).float() / 255 for frame in frames]
        tensors = [
            torch.from_numpy(np.array(frame, copy=True)).permute(2, 0, 1).float() / 255
            if not isinstance(frame, torch.Tensor)
            else frame
            for frame in tensors
        ]
        while len(tensors) < self.frames_per_video:
            tensors.append(tensors[-1].clone())
        return torch.stack(tensors[: self.frames_per_video]), torch.tensor(int(record["label"]), dtype=torch.long)

In [ ]:
from pathlib import Path

file = Path("/content/deep-fake-shield/ml/data/video_dataset.py")

text = file.read_text()

old = '''        if self.transform is not None:
            tensors = [self.transform(frame) for frame in frames]
        else:
            tensors = [torch.from_numpy(np.array(frame, copy=True)).permute(2, 0, 1).float() / 255 for frame in frames]
        tensors = [
            torch.from_numpy(np.array(frame, copy=True)).permute(2, 0, 1).float() / 255
            if not isinstance(frame, torch.Tensor)
            else frame
            for frame in tensors
        ]
'''

new = '''        # Ensure every frame has the same spatial dimensions.
        # EfficientNet-B0 expects a consistent image size.
        if self.transform is not None:
            tensors = [self.transform(frame) for frame in frames]
        else:
            tensors = []
            for frame in frames:
                frame = frame.resize((224, 224), Image.Resampling.BILINEAR)
                array = np.array(frame, copy=True)
                tensor = torch.from_numpy(array).permute(2, 0, 1).float() / 255.0
                tensors.append(tensor)

        # Make sure transformed tensors also have consistent dimensions.
        normalized_tensors = []
        for tensor in tensors:
            if not isinstance(tensor, torch.Tensor):
                tensor = torch.from_numpy(
                    np.array(tensor, copy=True)
                ).permute(2, 0, 1).float() / 255.0

            if tensor.ndim == 3 and tensor.shape[-2:] != (224, 224):
                tensor = torch.nn.functional.interpolate(
                    tensor.unsqueeze(0),
                    size=(224, 224),
                    mode="bilinear",
                    align_corners=False,
                ).squeeze(0)

            normalized_tensors.append(tensor)

        tensors = normalized_tensors
'''

if old not in text:
    print("ERROR: Expected code block was not found.")
else:
    file.write_text(text.replace(old, new))
    print("video_dataset.py updated successfully.")

video_dataset.py updated successfully.

In [ ]:
%cd /content/deep-fake-shield

!nl -ba ml/data/video_dataset.py | sed -n '80,130p'

/content/deep-fake-shield
    80	            image = crop if crop is not None else frame
    81	            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    82	            frames.append(Image.fromarray(image))
    83	        capture.release()
    84	        if not frames:
    85	            frames = [Image.fromarray(np.zeros((224, 224, 3), dtype=np.uint8))]
    86	        # Ensure every frame has the same spatial dimensions.
    87	        # EfficientNet-B0 expects a consistent image size.
    88	        if self.transform is not None:
    89	            tensors = [self.transform(frame) for frame in frames]
    90	        else:
    91	            tensors = []
    92	            for frame in frames:
    93	                frame = frame.resize((224, 224), Image.Resampling.BILINEAR)
    94	                array = np.array(frame, copy=True)
    95	                tensor = torch.from_numpy(array).permute(2, 0, 1).float() / 255.0
    96	                tensors.append(tensor)
    97
    98	        # Make sure transformed tensors also have consistent dimensions.
    99	        normalized_tensors = []
   100	        for tensor in tensors:
   101	            if not isinstance(tensor, torch.Tensor):
   102	                tensor = torch.from_numpy(
   103	                    np.array(tensor, copy=True)
   104	                ).permute(2, 0, 1).float() / 255.0
   105
   106	            if tensor.ndim == 3 and tensor.shape[-2:] != (224, 224):
   107	                tensor = torch.nn.functional.interpolate(
   108	                    tensor.unsqueeze(0),
   109	                    size=(224, 224),
   110	                    mode="bilinear",
   111	                    align_corners=False,
   112	                ).squeeze(0)
   113
   114	            normalized_tensors.append(tensor)
   115
   116	        tensors = normalized_tensors
   117	        while len(tensors) < self.frames_per_video:
   118	            tensors.append(tensors[-1].clone())
   119	        return torch.stack(tensors[: self.frames_per_video]), torch.tensor(int(record["label"]), dtype=torch.long)

In [ ]:
%cd /content/deep-fake-shield

!nl -ba ml/data/video_dataset.py | sed -n '1,130p'

/content/deep-fake-shield
     1	"""Lazy video-frame dataset with deterministic sampling and face crops."""
     2
     3	from __future__ import annotations
     4
     5	import csv
     6	from pathlib import Path
     7	from typing import Any
     8
     9	import cv2
    10	import numpy as np
    11	import torch
    12	from PIL import Image
    13	from torch.utils.data import Dataset
    14
    15
    16	def sample_frame_indices(frame_count: int, count: int) -> np.ndarray:
    17	    if frame_count <= 0:
    18	        return np.zeros(count, dtype=np.int64)
    19	    return np.linspace(0, max(frame_count - 1, 0), count, dtype=np.int64)
    20
    21
    22	class FaceCropper:
    23	    def __init__(self, margin: float = 0.2) -> None:
    24	        self.margin = margin
    25	        cascade_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    26	        self.detector = cv2.CascadeClassifier(cascade_path)
    27
    28	    def crop(self, frame: np.ndarray) -> np.ndarray | None:
    29	        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    30	        faces = self.detector.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(32, 32))
    31	        if len(faces) == 0:
    32	            return None
    33	        x, y, width, height = max(faces, key=lambda box: int(box[2]) * int(box[3]))
    34	        pad_x, pad_y = int(width * self.margin), int(height * self.margin)
    35	        top, bottom = max(0, y - pad_y), min(frame.shape[0], y + height + pad_y)
    36	        left, right = max(0, x - pad_x), min(frame.shape[1], x + width + pad_x)
    37	        return frame[top:bottom, left:right]
    38
    39
    40	class VideoFrameDataset(Dataset[tuple[torch.Tensor, torch.Tensor]]):
    41	    def __init__(self, csv_path: Path, frames_per_video: int = 4, transform: Any = None, video_root: Path | None = None) -> None:
    42	        with csv_path.open(newline="", encoding="utf-8") as csv_file:
    43	            self.records = list(csv.DictReader(csv_file))
    44	        self.frames_per_video = frames_per_video
    45	        self.transform = transform
    46	        self.video_root = video_root
    47	        self.cropper = FaceCropper()
    48
    49	    def resolve_video_path(self, path: str) -> Path:
    50	        original = Path(path)
    51	        if original.exists() or self.video_root is None:
    52	            return original
    53	        marker = Path("datasets/raw")
    54	        try:
    55	            relative = Path(*original.parts[original.parts.index(marker.parts[0]) :])
    56	            marker_index = next(index for index in range(len(original.parts) - 1) if Path(*original.parts[index : index + 2]) == marker)
    57	            relative = Path(*original.parts[marker_index + len(marker.parts) :])
    58	            candidate = self.video_root / relative
    59	            if candidate.exists():
    60	                return candidate
    61	        except (ValueError, StopIteration):
    62	            pass
    63	        candidate = self.video_root / original.name
    64	        return candidate if candidate.exists() else original
    65
    66	    def __len__(self) -> int:
    67	        return len(self.records)
    68
    69	    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
    70	        record = self.records[index]
    71	        capture = cv2.VideoCapture(str(self.resolve_video_path(record["video_path"])))
    72	        frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    73	        frames = []
    74	        for frame_index in sample_frame_indices(frame_count, self.frames_per_video):
    75	            capture.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
    76	            ok, frame = capture.read()
    77	            if not ok:
    78	                continue
    79	            crop = self.cropper.crop(frame)
    80	            image = crop if crop is not None else frame
    81	            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    82	            frames.append(Image.fromarray(image))
    83	        capture.release()
    84	        if not frames:
    85	            frames = [Image.fromarray(np.zeros((224, 224, 3), dtype=np.uint8))]
    86	        if self.transform is not None:
    87	            tensors = [self.transform(frame) for frame in frames]
    88	        else:
    89	            tensors = [torch.from_numpy(np.array(frame, copy=True)).permute(2, 0, 1).float() / 255 for frame in frames]
    90	        tensors = [
    91	            torch.from_numpy(np.array(frame, copy=True)).permute(2, 0, 1).float() / 255
    92	            if not isinstance(frame, torch.Tensor)
    93	            else frame
    94	            for frame in tensors
    95	        ]
    96	        while len(tensors) < self.frames_per_video:
    97	            tensors.append(tensors[-1].clone())
    98	        return torch.stack(tensors[: self.frames_per_video]), torch.tensor(int(record["label"]), dtype=torch.long)

In [ ]:
from pathlib import Path

file = Path("/content/deep-fake-shield/ml/data/video_dataset.py")

text = file.read_text()

start = text.index("    def __getitem__(self, index: int)")

new_method = '''    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        record = self.records[index]

        video_path = self.resolve_video_path(record["video_path"])
        capture = cv2.VideoCapture(str(video_path))

        frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)

        frames = []

        for frame_index in sample_frame_indices(
            frame_count, self.frames_per_video
        ):
            capture.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            ok, frame = capture.read()

            if not ok:
                continue

            crop = self.cropper.crop(frame)
            image = crop if crop is not None else frame

            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

            # Force every frame to the same size.
            image = cv2.resize(
                image,
                (224, 224),
                interpolation=cv2.INTER_LINEAR,
            )

            frames.append(Image.fromarray(image))

        capture.release()

        if not frames:
            frames = [
                Image.fromarray(
                    np.zeros((224, 224, 3), dtype=np.uint8)
                )
            ]

        tensors = []

        for frame in frames:

            # Always enforce 224x224 before transform.
            frame = frame.resize(
                (224, 224),
                Image.Resampling.BILINEAR,
            )

            if self.transform is not None:
                tensor = self.transform(frame)
            else:
                array = np.array(frame, copy=True)
                tensor = (
                    torch.from_numpy(array)
                    .permute(2, 0, 1)
                    .float()
                    / 255.0
                )

            # Convert non-tensor output if necessary.
            if not isinstance(tensor, torch.Tensor):
                tensor = torch.from_numpy(
                    np.array(tensor, copy=True)
                )

                if tensor.ndim == 3 and tensor.shape[-1] in (1, 3):
                    tensor = tensor.permute(2, 0, 1)

                tensor = tensor.float() / 255.0

            # Final safety resize.
            if tensor.ndim == 3 and tensor.shape[-2:] != (224, 224):
                tensor = torch.nn.functional.interpolate(
                    tensor.unsqueeze(0),
                    size=(224, 224),
                    mode="bilinear",
                    align_corners=False,
                ).squeeze(0)

            tensors.append(tensor)

        # Duplicate the final frame if necessary.
        while len(tensors) < self.frames_per_video:
            tensors.append(tensors[-1].clone())

        return (
            torch.stack(tensors[: self.frames_per_video]),
            torch.tensor(
                int(record["label"]),
                dtype=torch.long,
            ),
        )
'''

file.write_text(text[:start] + new_method + "\n")

print("✅ video_dataset.py has been fixed.")

✅ video_dataset.py has been fixed.

In [ ]:
from pathlib import Path
import sys
import time

REPO_ROOT = Path("/content/deep-fake-shield")
DATA_ROOT = Path("/content/drive/MyDrive/DeepFake-Shield/datasets/raw")
TRAIN_CSV = REPO_ROOT / "artifacts/splits/train.csv"

sys.path.insert(0, str(REPO_ROOT))

from ml.data.video_dataset import VideoFrameDataset

dataset = VideoFrameDataset(
    TRAIN_CSV,
    frames_per_video=2,
    transform=None,
    video_root=DATA_ROOT
)

print("Dataset length:", len(dataset))

start = time.time()

sample = dataset[0]

elapsed = time.time() - start

print("Loaded in:", round(elapsed, 2), "seconds")
print("Frames shape:", sample[0].shape)
print("Label:", sample[1])

Dataset length: 4207
Loaded in: 0.6 seconds
Frames shape: torch.Size([2, 3, 224, 224])
Label: tensor(1)

In [ ]:
start = time.time()

sample = dataset[0]

print("First sample loaded in:", time.time() - start, "seconds")
print("Sample type:", type(sample))

if isinstance(sample, tuple):
    print("Number of returned items:", len(sample))
    for i, item in enumerate(sample):
        print(i, type(item), getattr(item, "shape", None))

First sample loaded in: 0.292527437210083 seconds
Sample type: <class 'tuple'>
Number of returned items: 2
0 <class 'torch.Tensor'> torch.Size([2, 3, 224, 224])
1 <class 'torch.Tensor'> torch.Size([])

In [ ]:
from ml.data.video_dataset import VideoFrameDataset
import time

dataset = VideoFrameDataset(
    TRAIN_CSV,
    frames_per_video=2,
    transform=None,
    video_root=DATA_ROOT
)

print("Dataset length:", len(dataset))

start = time.time()

sample = dataset[0]

print("Time:", round(time.time() - start, 2), "seconds")
print("Shape:", sample[0].shape)
print("Label:", sample[1])

Dataset length: 4207
Time: 0.98 seconds
Shape: torch.Size([2, 3, 224, 224])
Label: tensor(1)

In [ ]:
%cd /content/deep-fake-shield

!python scripts/train_baseline.py \
    --train-csv artifacts/splits/train.csv \
    --val-csv artifacts/splits/val.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --pretrained \
    --epochs 2 \
    --limit 1000 \
    --frames-per-video 2 \
    --batch-size 16 \
    --workers 2 \
    --output-dir artifacts/experiments/submission_final

/content/deep-fake-shield
{
  "epoch": 1,
  "train": {
    "accuracy": 0.7855711422845691,
    "precision": 0.7930327868852459,
    "recall": 0.774,
    "f1": 0.7834008097165992,
    "roc_auc": 0.8667710843373494,
    "pr_auc": 0.8700386414362444,
    "false_positive_rate": 0.20281124497991967,
    "false_negative_rate": 0.226,
    "support": 998,
    "loss": 0.5058757006405351
  },
  "validation": {
    "accuracy": 0.541019955654102,
    "precision": 0.9635036496350365,
    "recall": 0.4981132075471698,
    "f1": 0.6567164179104478,
    "roc_auc": 0.7920648915535179,
    "pr_auc": 0.9589464739232781,
    "false_positive_rate": 0.14018691588785046,
    "false_negative_rate": 0.5018867924528302,
    "support": 902,
    "loss": 0.7935367470768233
  }
}
{
  "epoch": 2,
  "train": {
    "accuracy": 0.9218436873747495,
    "precision": 0.9359504132231405,
    "recall": 0.906,
    "f1": 0.9207317073170732,
    "roc_auc": 0.971710843373494,
    "pr_auc": 0.9703615420662247,
    "false_positive_rate": 0.06224899598393574,
    "false_negative_rate": 0.094,
    "support": 998,
    "loss": 0.2327459248339007
  },
  "validation": {
    "accuracy": 0.5953436807095344,
    "precision": 0.9714912280701754,
    "recall": 0.5572327044025157,
    "f1": 0.7082334132693845,
    "roc_auc": 0.8231117380826426,
    "pr_auc": 0.9673760381830789,
    "false_positive_rate": 0.12149532710280374,
    "false_negative_rate": 0.4427672955974843,
    "support": 902,
    "loss": 0.8864764787934043
  }
}
device=cuda output=artifacts/experiments/submission_final

In [ ]:
%cd /content/deep-fake-shield

!python scripts/evaluate_baseline.py \
    --csv artifacts/splits/test.csv \
    --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
    --checkpoint artifacts/experiments/submission_final/best_model.pt \
    --frames 2 \
    --limit 902 \
    --output-dir artifacts/evaluation/submission_final

/content/deep-fake-shield
{
  "device": "cuda",
  "videos": 902,
  "metrics": {
    "accuracy": 0.5543237250554324,
    "precision": 0.9734939759036144,
    "recall": 0.5081761006289308,
    "f1": 0.6677685950413224,
    "roc_auc": 0.830094633515547,
    "pr_auc": 0.9679018227235412,
    "false_positive_rate": 0.102803738317757,
    "false_negative_rate": 0.4918238993710692,
    "support": 902
  }
}

### This is your main training run.

It uses:

```text
4,207 training videos
902 validation videos
4 frames/video
5 epochs
GPU
```

The test set is **not used during training**.

---

# Important: Watch the output

You should see training progress similar to:

```text
Epoch 1/5
Training ...
Validation ...

Epoch 2/5
Training ...
Validation ...

...
```

and eventually:

```text
best_model.pt
```

### Don't close the Colab tab while this is running.

Also, don't run another training cell simultaneously.

---

# CELL 26 — Check the trained model

After training completes:

In [ ]:
from pathlib import Path

FULL_DIR = (
    REPO_ROOT
    / "artifacts"
    / "experiments"
    / "submission_v1"
)

print("Training directory:", FULL_DIR)

for item in sorted(FULL_DIR.iterdir()):
    print(
        item.name,
        "→",
        round(item.stat().st_size / 1024**2, 2),
        "MB"
        if item.is_file()
        else ""
    )

Training directory: /content/deep-fake-shield/artifacts/experiments/submission_v1

Find:

```text
best_model.pt
```

---

# CELL 27 — FINAL TEST

Now evaluate against your **untouched 902-video test set**.

In [ ]:
if (FULL_DIR / "best_model.pt").exists():
    !python scripts/evaluate_baseline.py \
        --csv artifacts/splits/test.csv \
        --video-root "/content/drive/MyDrive/DeepFake-Shield/datasets/raw" \
        --checkpoint artifacts/experiments/submission_v1/best_model.pt \
        --frames 4 \
        --limit 0 \
        --output-dir artifacts/evaluation/submission_v1
else:
    print("Full training not completed or best_model.pt not found. Cannot perform final test.")

Full training not completed or best_model.pt not found. Cannot perform final test.

This is your final evaluation.

---

# CELL 28 — Display final metrics

In [ ]:
import json
from pathlib import Path

FINAL_METRICS = (
    REPO_ROOT
    / "artifacts"
    / "evaluation"
    / "submission_v1"
    / "test_metrics.json"
)

if not FINAL_METRICS.exists():

    print(
        "❌ Final metrics file not found:"
    )

    print(FINAL_METRICS)

else:

    metrics = json.loads(
        FINAL_METRICS.read_text()
    )

    print(
        json.dumps(
            metrics,
            indent=2
        )
    )

❌ Final metrics file not found:
/content/deep-fake-shield/artifacts/evaluation/submission_v1/test_metrics.json

### Save this output.

These are the numbers you'll want for your project presentation/submission.

---

# CELL 29 — Test a real video

In [ ]:
real_videos = []

for folder_name in [
    "Celeb-real",
    "YouTube-real"
]:

    folder = DATA_ROOT / folder_name

    if folder.exists():

        real_videos.extend(
            folder.glob("*.mp4")
        )

print("Real videos found:", len(real_videos))

if real_videos:
    print("Sample:", real_videos[0])

Real videos found: 712
Sample: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-real/1.mp4

---

# CELL 30 — Test a fake video

In [ ]:
fake_videos = list(
    (DATA_ROOT / "Celeb-Youtube-fake").glob("*.mp4")
)

print("Fake videos found:", len(fake_videos))

if fake_videos:
    print("Sample:", fake_videos[0])

Fake videos found: 5299
Sample: /content/drive/MyDrive/DeepFake-Shield/datasets/raw/Celeb-Youtube-fake/4866.mp4

---

# CELL 31 — Run inference on a fake video

In [ ]:
if fake_videos and (FULL_DIR / "best_model.pt").exists():
    fake_video = fake_videos[0]

    print("Testing:")
    print(fake_video)

    !python scripts/infer_video.py \
        --video "{fake_video}" \
        --checkpoint artifacts/experiments/submission_v1/best_model.pt \
        --frames 4
else:
    print("Fake video list is empty or full training model not found. Cannot run inference.")

Fake video list is empty or full training model not found. Cannot run inference.

---

# CELL 32 — Run inference on a real video

In [ ]:
if real_videos and (FULL_DIR / "best_model.pt").exists():
    real_video = real_videos[0]

    print("Testing:")
    print(real_video)

    !python scripts/infer_video.py \
        --video "{real_video}" \
        --checkpoint artifacts/experiments/submission_v1/best_model.pt \
        --frames 4
else:
    print("Real video list is empty or full training model not found. Cannot run inference.")

Real video list is empty or full training model not found. Cannot run inference.

You want the model to distinguish the two correctly.

---

# CELL 33 — Copy production model to Google Drive

In [ ]:
from pathlib import Path
import shutil

# Paths
MODEL_SRC = Path(
    "/content/deep-fake-shield/artifacts/experiments/submission_final/best_model.pt"
)

DRIVE_MODEL_ROOT = Path(
    "/content/drive/MyDrive/DeepFake-Shield/models"
)

# Create Drive models directory
DRIVE_MODEL_ROOT.mkdir(parents=True, exist_ok=True)

# Production model name
PRODUCTION_MODEL = DRIVE_MODEL_ROOT / "deepfake_shield_video_v1.pt"

# Check source model exists
if not MODEL_SRC.exists():
    raise FileNotFoundError(f"Model not found: {MODEL_SRC}")

# Copy model to Google Drive
shutil.copy2(MODEL_SRC, PRODUCTION_MODEL)

print("✅ Model copied successfully!")
print(f"📦 Model: {PRODUCTION_MODEL}")
print(f"📏 Size: {PRODUCTION_MODEL.stat().st_size / (1024**2):.2f} MB")

✅ Model copied successfully!
📦 Model: /content/drive/MyDrive/DeepFake-Shield/models/deepfake_shield_video_v1.pt
📏 Size: 15.58 MB

In [ ]:
from pathlib import Path

PRODUCTION_MODEL = Path(
    "/content/drive/MyDrive/DeepFake-Shield/models/deepfake_shield_video_v1.pt"
)

print("Exists:", PRODUCTION_MODEL.exists())
print("Path:", PRODUCTION_MODEL)
print("Size:", f"{PRODUCTION_MODEL.stat().st_size / (1024**2):.2f} MB")

Exists: True
Path: /content/drive/MyDrive/DeepFake-Shield/models/deepfake_shield_video_v1.pt
Size: 15.58 MB

In [ ]:
import shutil
from pathlib import Path

SOURCE_MODEL = (
    REPO_ROOT
    / "artifacts"
    / "experiments"
    / "submission_v1"
    / "best_model.pt"
)

PRODUCTION_MODEL = (
    DRIVE_MODEL_ROOT
    / "deepfake_shield_video_v1.pt"
)

if not SOURCE_MODEL.exists():
    raise FileNotFoundError(
        f"Model not found: {SOURCE_MODEL}"
    )

shutil.copy2(
    SOURCE_MODEL,
    PRODUCTION_MODEL
)

print("✅ Production model saved:")
print(PRODUCTION_MODEL)

print(
    "Size:",
    round(
        PRODUCTION_MODEL.stat().st_size / 1024**2,
        2
    ),
    "MB"
)

NameError: name 'DRIVE_MODEL_ROOT' is not defined

Now your model is permanently in:

```text
Google Drive
└── DeepFake-Shield/
    └── models/
        └── deepfake_shield_video_v1.pt
```

---

# CELL 34 — Download model to Mac

In [ ]:
from google.colab import files

files.download(
    "/content/drive/MyDrive/DeepFake-Shield/models/deepfake_shield_video_v1.pt"
)

FileNotFoundError: Cannot find file: /content/drive/MyDrive/DeepFake-Shield/models/deepfake_shield_video_v1.pt

Put the downloaded file into your local project.

For example:

```text
deep-fake-shield/
│
├── backend/
│   ├── main.py
│   ├── inference.py
│   └── models/
│       └── deepfake_shield_video_v1.pt
│
└── frontend/
```

---

# CELL 35 — Save final metrics to Drive

In [ ]:
FINAL_REPORT_DIR = (
    Path("/content/drive/MyDrive/DeepFake-Shield")
    / "submission_results"
)

FINAL_REPORT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

if FINAL_METRICS.exists():

    shutil.copy2(
        FINAL_METRICS,
        FINAL_REPORT_DIR / "test_metrics.json"
    )

    print(
        "✅ Metrics saved to:",
        FINAL_REPORT_DIR / "test_metrics.json"
    )

---

# Your final project state

After everything succeeds, you'll have:

```text
                    DeepFake Shield
                           │
             ┌─────────────┴─────────────┐
             │                           │
         FRONTEND                    BACKEND
          ✅ DONE                      ✅ DONE
                                         │
                                         ▼
                                  MODEL INFERENCE
                                         │
                                         ▼
                              deepfake_shield_video_v1.pt
                                         │
                                         ▼
                              REAL / FAKE + CONFIDENCE
```

And your ML results:

```text
Dataset
│
├── 5,299 fake
├──   712 real
└── 6,011 labeled
       │
       ▼
Train: 4,207
Val:     902
Test:    902
       │
       ▼
Pretrained Deep Learning Model
       │
       ▼
5 epochs
       │
       ▼
best_model.pt
       │
       ▼
902-video final test
       │
       ▼
Metrics
       │
       ▼
Production model
```